Mversion: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/.github/actions/slack'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    directory: '/.github/actions/setup/directories'
    schedule:
      interval: 'daily'    
  - package-ecosystem: 'cargo'
    directory: '/yjit'
    schedule:
      interval: 'daily'
[![CodeQL](https://github.com/Milanhe92/AI-alati/actions/workflows/codeql-analysis.yml/badge.svg)](https://github.com/Milanhe92/AI-alati/actions/workflows/codeql-analysis.yml)
